# Generated by Django 2.2.11 on 2020-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaffoldApp', '0004_auto_20200401_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addsupplier',
            name='supplierContact1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='addsupplier',
            name='supplierContact2',
            field=models.CharField(max_length=30),
        ),
    ]
