# Generated by Django 3.0.5 on 2020-04-22 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ScaffoldApp', '0005_auto_20200401_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='stock',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
